### ISSUE TITLE
error inserting channels pq: invalid byte sequence for encoding "UTF8": 0x91

### ISSUE THREAD

**Issue by mb300sd** [fiatjaf/mcldsp#3]
I'm getting this error trying to migrate my database with the latest 149 release.

`error inserting channels pq: invalid byte sequence for encoding "UTF8": 0x91`

If I add ?binary_parameters=yes to the connection, I get

`error inserting channels pq: incorrect binary data format in bind parameter 26`

Which is 
`PerCommitRemote:               {0x2, 0x91, 0xfd, 0x74, 0x3a, 0x38, 0x81, 0x10, 0x4, 0x21, 0xd0, 0x23, 0x9c, 0x73, 0xf4, 0x42, 0x2f, 0x32, 0x7a, 0xb2, 0x38, 0x46, 0x88, 0x5d, 0x80, 0xcc, 0xd, 0xf6, 0x2, 0x9, 0x9b, 0xae, 0x65},`

Not sure why it's doing anything with UTF8 on a bytea column.

**Comment by fiatjaf** [comment]
After many hours looking at this I have no idea of what is happening.

**Comment by mb300sd** [comment]
Spent quite a few hours with my myself too. Happens with psql 11 and 13. 

Could this be a bug in the sqlx library? I'm not familiar with go at all.

Need to get this migrated, I'm having severe performance issues with sqlite because of the number of htlcs in the database when channels are closed (>1 year old, 30k+ forwards each). To the point where I'm down for 6 hours at a time, and it's a chain reaction with peers closing channels because of down time.

**Comment by mb300sd** [comment]
Thinking I might just have to start from scratch, lost most of my good inbound channels already.

**Comment by fiatjaf** [comment]
I'm reading the code for the postgres drivers, so maybe I'll have an answer in some minutes.
What is your node, out of curiosity?

**Comment by mb300sd** [comment]
Rather not dox my IP/location publicly, can shoot ya an email if it'll help.

**Comment by fiatjaf** [comment]
Ok, found the issue and fixed it in 2a1e12d. Apparently the "NamedExec" function of sqlx is broken or it doesn't do what I thought it would do (which is to allow me to not care about column ordering). It was trying to save `bytea` values in `text` columns.

So I replaced that with a manual listing of column names and ordering of paramters and everything worked.

**Comment by mb300sd** [comment]
Awesome!! It's working. I'm having to clean up some foreign key issues in channel_htlcs from deleted channels, probably because my sqlite database was created by a really old version, but so far so good.

Thanks!
